In [9]:
import os
os.getcwd()

'F:\\Project Data Master\\Python Files'

# Asteron Data Lab — Python/Pandas Problems 1–20

Dataset: ERP Customers

##1 — Load erp_customers.csv with pandas

In [5]:
import pandas as pd
customers = pd.read_csv(r"F:\Project Data Master\Asteron_Data_Lab_v1_Learner_Pack\raw\erp_customers.csv")
customers

,customer_id,customer_name,city,state,region,industry,customer_size,segment,credit_days,sales_rep_id,created_date,credit_limit_lakh
0,C00001,Trinity Fasteners Works,Nashik,Maharashtra,West,Aerospace,Micro,D,15,SR029,2021-06-09,12.02
1,C00002,Nova Fasteners Ltd,Bengaluru,Karnataka,South,Automotive,Small,C,30,SR005,2021-10-10,151.83
2,C00003,Royal Equipments Works,Nashik,Maharashtra,West,Electrical,Small,C,30,SR029,2018-05-16,123.22
3,C00004,Universal Equipments LLP,Ahmedabad,Gujarat,West,Industrial Machinery,Micro,D,15,SR001,2018-10-25,72.55
4,C00005,Metro Equipments Works,Bhopal,Madhya Pradesh,Central,Construction,Small,C,30,SR036,2022-11-12,8.01
...,...,...,...,...,...,...,...,...,...,...,...,...
5995,C05996,Kinetic Works Pvt Ltd,Pune,Maharashtra,West,Renewables,Micro,D,15,SR026,2019-01-29,23.92
5996,C05997,Western Tools Industries,Bengaluru,Karnataka,South,Fabrication,Medium,B,45,SR016,2025-02-04,88.34
5997,C05998,Dynamic Technologies Industries,Coimbatore,Tamil Nadu,South,Fabrication,Micro,D,15,SR016,2025-07-28,67.58
5998,C05999,Metro Solutions Works,Ahmedabad,Gujarat,West,Construction,Large,A,60,SR039,2018-05-30,61.49
5999,C06000,Western Industries Works,Chennai,Tamil Nadu,South,Construction,Small,C,30,SR005,2020-12-31,102.47

##2. Display first 10 rows.

In [7]:
import pandas as pd
customers =pd.read_csv(r"F:\Project Data Master\Asteron_Data_Lab_v1_Learner_Pack\raw\erp_customers.csv")
customers.head(10)

,customer_id,customer_name,city,state,region,industry,customer_size,segment,credit_days,sales_rep_id,created_date,credit_limit_lakh
0,C00001,Trinity Fasteners Works,Nashik,Maharashtra,West,Aerospace,Micro,D,15,SR029,2021-06-09,12.02
1,C00002,Nova Fasteners Ltd,Bengaluru,Karnataka,South,Automotive,Small,C,30,SR005,2021-10-10,151.83
2,C00003,Royal Equipments Works,Nashik,Maharashtra,West,Electrical,Small,C,30,SR029,2018-05-16,123.22
3,C00004,Universal Equipments LLP,Ahmedabad,Gujarat,West,Industrial Machinery,Micro,D,15,SR001,2018-10-25,72.55
4,C00005,Metro Equipments Works,Bhopal,Madhya Pradesh,Central,Construction,Small,C,30,SR036,2022-11-12,8.01
5,C00006,Sterling Systems Private Limited,Ahmedabad,Gujarat,West,Automotive,Large,A,60,SR032,2022-05-21,153.75
6,C00007,Royal Tools Works,Ludhiana,Punjab,North,Industrial Machinery,Medium,B,45,SR030,2025-06-25,165.82
7,C00008,Galaxy Works Ltd,Pune,Maharashtra,West,Electrical,Small,C,30,SR034,2019-02-28,63.05
8,C00009,Vertex Industries Ltd,Ludhiana,Punjab,North,Automotive,Medium,B,45,SR030,2026-03-18,107.97
9,C00010,Apex Enterprises Works,Mumbai,Maharashtra,West,General Engineering,Medium,B,45,SR041,2021-02-02,271.00

##3. Display last 10 rows.

In [10]:
import pandas as pd
customers = pd.read_csv(r"F:\Project Data Master\Asteron_Data_Lab_v1_Learner_Pack\raw\erp_customers.csv")
customers.tail(10)

,customer_id,customer_name,city,state,region,industry,customer_size,segment,credit_days,sales_rep_id,created_date,credit_limit_lakh
5990,C05991,Indus Tools Industries,Ludhiana,Punjab,North,Renewables,Large,A,60,SR022,2025-04-06,406.23
5991,C05992,Apex Solutions Works,Delhi,Delhi,North,Railways,Small,C,30,SR007,2022-03-29,53.31
5992,C05993,Fusion Industries Pvt Ltd,Pune,Maharashtra,West,Consumer Durables,Large,A,60,SR013,2018-09-04,194.74
5993,C05994,Apex Machines LLP,Pune,Maharashtra,West,Consumer Durables,Micro,D,15,SR034,2023-07-16,71.62
5994,C05995,Kinetic Machines Pvt Ltd,Pune,Maharashtra,West,Automotive,Micro,D,15,SR009,2026-03-10,27.53
5995,C05996,Kinetic Works Pvt Ltd,Pune,Maharashtra,West,Renewables,Micro,D,15,SR026,2019-01-29,23.92
5996,C05997,Western Tools Industries,Bengaluru,Karnataka,South,Fabrication,Medium,B,45,SR016,2025-02-04,88.34
5997,C05998,Dynamic Technologies Industries,Coimbatore,Tamil Nadu,South,Fabrication,Micro,D,15,SR016,2025-07-28,67.58
5998,C05999,Metro Solutions Works,Ahmedabad,Gujarat,West,Construction,Large,A,60,SR039,2018-05-30,61.49
5999,C06000,Western Industries Works,Chennai,Tamil Nadu,South,Construction,Small,C,30,SR005,2020-12-31,102.47

##4. Show shape of the DataFrame.

In [11]:
customers.shape

(6000, 12)

##5. List column names.

In [17]:
customers.columns

Index(['customer_id', 'customer_name', 'city', 'state', 'region', 'industry',
       'customer_size', 'segment', 'credit_days', 'sales_rep_id',
       'created_date', 'credit_limit_lakh'],
      dtype='object')

In [14]:
for column in customers.columns:
    print(column)

customer_id
customer_name
city
state
region
industry
customer_size
segment
credit_days
sales_rep_id
created_date
credit_limit_lakh

In [16]:
pd.DataFrame(customers.columns, columns=["Columns"])

              Columns
0         customer_id
1       customer_name
2                city
3               state
4              region
5            industry
6       customer_size
7             segment
8         credit_days
9        sales_rep_id
10       created_date
11  credit_limit_lakh

##6. Inspect dtypes.

In [22]:
customers.dtypes.reset_index().rename(columns={"index":"Columns",0:"Data Type"})

              Columns Data Type
0         customer_id    object
1       customer_name    object
2                city    object
3               state    object
4              region    object
5            industry    object
6       customer_size    object
7             segment    object
8         credit_days     int64
9        sales_rep_id    object
10       created_date    object
11  credit_limit_lakh   float64

##7. Use info() to inspect missing values.

In [24]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        6000 non-null   object
 1   customer_name      6000 non-null   object
 2   city               6000 non-null   object
 3   state              6000 non-null   object
 4   region             6000 non-null   object
 5   industry           6000 non-null   object
 6   customer_size      6000 non-null   object
 7   segment            6000 non-null   object
 8   credit_days        6000 non-null   int64
 9   sales_rep_id       6000 non-null   object
 10  created_date       6000 non-null   object
 11  credit_limit_lakh  6000 non-null   float64
dtypes: float64(1), int64(1), object(10)
memory usage: 562.6+ KB

##8. Generate descriptive statistics.

In [27]:
customers.head()

,customer_id,customer_name,city,state,region,industry,customer_size,segment,credit_days,sales_rep_id,created_date,credit_limit_lakh
0,C00001,Trinity Fasteners Works,Nashik,Maharashtra,West,Aerospace,Micro,D,15,SR029,2021-06-09,12.02
1,C00002,Nova Fasteners Ltd,Bengaluru,Karnataka,South,Automotive,Small,C,30,SR005,2021-10-10,151.83
2,C00003,Royal Equipments Works,Nashik,Maharashtra,West,Electrical,Small,C,30,SR029,2018-05-16,123.22
3,C00004,Universal Equipments LLP,Ahmedabad,Gujarat,West,Industrial Machinery,Micro,D,15,SR001,2018-10-25,72.55
4,C00005,Metro Equipments Works,Bhopal,Madhya Pradesh,Central,Construction,Small,C,30,SR036,2022-11-12,8.01

In [26]:
customers.describe()

       credit_days  credit_limit_lakh
count  6000.000000        6000.000000
mean     35.287500         219.377243
std      17.015525         373.959048
min      15.000000           2.010000
25%      15.000000          43.487500
50%      30.000000          87.365000
75%      45.000000         221.152500
max      75.000000        2796.730000

In [29]:
customers.describe(include="all")

,customer_id,customer_name,city,state,region,industry,customer_size,segment,credit_days,sales_rep_id,created_date,credit_limit_lakh
count,6000,6000,6000,6000,6000,6000,6000,6000,6000.000000,6000,6000,6000.000000
unique,6000,2535,20,11,5,10,5,5,NaN,45,2576,NaN
top,C05984,Sigma Manufacturing Industries,Pune,Maharashtra,West,Automotive,Small,C,NaN,SR005,2019-02-28,NaN
freq,1,8,935,2367,2840,1348,1955,1955,NaN,342,8,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.287500,NaN,NaN,219.377243
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.015525,NaN,NaN,373.959048
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,NaN,2.010000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,NaN,43.487500
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,NaN,NaN,87.365000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.000000,NaN,NaN,221.152500
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.000000,NaN,NaN,2796.730000

##9. Select customer_id and customer_name.

In [34]:
customers[["customer_id","customer_name"]]

     customer_id                    customer_name
0         C00001          Trinity Fasteners Works
1         C00002               Nova Fasteners Ltd
2         C00003           Royal Equipments Works
3         C00004         Universal Equipments LLP
4         C00005           Metro Equipments Works
...          ...                              ...
5995      C05996            Kinetic Works Pvt Ltd
5996      C05997         Western Tools Industries
5997      C05998  Dynamic Technologies Industries
5998      C05999            Metro Solutions Works
5999      C06000         Western Industries Works

[6000 rows x 2 columns]

##10. Filter Pune customers.

In [46]:
customers[customers['city'] =="Pune"]

,customer_id,customer_name,city,state,region,industry,customer_size,segment,credit_days,sales_rep_id,created_date,credit_limit_lakh
7,C00008,Galaxy Works Ltd,Pune,Maharashtra,West,Electrical,Small,C,30,SR034,2019-02-28,63.05
16,C00017,Supreme Works Industries,Pune,Maharashtra,West,Automotive,Medium,B,45,SR014,2018-10-04,207.53
27,C00028,Reliable Engineering Pvt Ltd,Pune,Maharashtra,West,Electrical,Medium,B,45,SR003,2018-02-07,183.60
32,C00033,Zenith Equipments Ltd,Pune,Maharashtra,West,Automotive,Micro,D,15,SR026,2022-05-04,51.82
33,C00034,Galaxy Engineering Private Limited,Pune,Maharashtra,West,Aerospace,Large,A,60,SR002,2020-07-17,99.45
...,...,...,...,...,...,...,...,...,...,...,...,...
5988,C05989,Bharat Auto Parts Pvt Ltd,Pune,Maharashtra,West,Automotive,Medium,B,45,SR031,2019-05-21,318.75
5992,C05993,Fusion Industries Pvt Ltd,Pune,Maharashtra,West,Consumer Durables,Large,A,60,SR013,2018-09-04,194.74
5993,C05994,Apex Machines LLP,Pune,Maharashtra,West,Consumer Durables,Micro,D,15,SR034,2023-07-16,71.62
5994,C05995,Kinetic Machines Pvt Ltd,Pune,Maharashtra,West,Automotive,Micro,D,15,SR009,2026-03-10,27.53
5995,C05996,Kinetic Works Pvt Ltd,Pune,Maharashtra,West,Renewables,Micro,D,15,SR026,2019-01-29,23.92

##11. Filter Maharashtra customers.

In [54]:
customers[customers["state"] == "Maharashtra"]

,customer_id,customer_name,city,state,region,industry,customer_size,segment,credit_days,sales_rep_id,created_date,credit_limit_lakh
0,C00001,Trinity Fasteners Works,Nashik,Maharashtra,West,Aerospace,Micro,D,15,SR029,2021-06-09,12.02
2,C00003,Royal Equipments Works,Nashik,Maharashtra,West,Electrical,Small,C,30,SR029,2018-05-16,123.22
7,C00008,Galaxy Works Ltd,Pune,Maharashtra,West,Electrical,Small,C,30,SR034,2019-02-28,63.05
9,C00010,Apex Enterprises Works,Mumbai,Maharashtra,West,General Engineering,Medium,B,45,SR041,2021-02-02,271.00
12,C00013,Trinity Enterprises Ltd,Mumbai,Maharashtra,West,Automotive,Micro,D,15,SR019,2020-07-19,27.57
...,...,...,...,...,...,...,...,...,...,...,...,...
5988,C05989,Bharat Auto Parts Pvt Ltd,Pune,Maharashtra,West,Automotive,Medium,B,45,SR031,2019-05-21,318.75
5992,C05993,Fusion Industries Pvt Ltd,Pune,Maharashtra,West,Consumer Durables,Large,A,60,SR013,2018-09-04,194.74
5993,C05994,Apex Machines LLP,Pune,Maharashtra,West,Consumer Durables,Micro,D,15,SR034,2023-07-16,71.62
5994,C05995,Kinetic Machines Pvt Ltd,Pune,Maharashtra,West,Automotive,Micro,D,15,SR009,2026-03-10,27.53
5995,C05996,Kinetic Works Pvt Ltd,Pune,Maharashtra,West,Renewables,Micro,D,15,SR026,2019-01-29,23.92

##12. Filter Large and Enterprise customers.

In [53]:
customers[customers["customer_size"].isin([ "Large","Enterprise"])]

,customer_id,customer_name,city,state,region,industry,customer_size,segment,credit_days,sales_rep_id,created_date,credit_limit_lakh
5,C00006,Sterling Systems Private Limited,Ahmedabad,Gujarat,West,Automotive,Large,A,60,SR032,2022-05-21,153.75
13,C00014,Supreme Solutions Pvt Ltd,Bhopal,Madhya Pradesh,Central,Automotive,Enterprise,A+,75,SR036,2018-06-07,338.78
22,C00023,Universal Manufacturing Ltd,Bengaluru,Karnataka,South,Automotive,Enterprise,A+,75,SR016,2023-11-01,1952.45
25,C00026,Bharat Tools Pvt Ltd,Ahmedabad,Gujarat,West,General Engineering,Large,A,60,SR015,2025-06-15,523.19
26,C00027,Vertex Projects Ltd,Indore,Madhya Pradesh,Central,Fabrication,Enterprise,A+,75,SR036,2021-02-23,1093.09
...,...,...,...,...,...,...,...,...,...,...,...,...
5985,C05986,Bharat Industries Works,Kolkata,West Bengal,East,Automotive,Large,A,60,SR001,2021-01-04,1096.73
5987,C05988,Mahalaxmi Components Ltd,Indore,Madhya Pradesh,Central,Fabrication,Large,A,60,SR020,2021-03-12,172.17
5990,C05991,Indus Tools Industries,Ludhiana,Punjab,North,Renewables,Large,A,60,SR022,2025-04-06,406.23
5992,C05993,Fusion Industries Pvt Ltd,Pune,Maharashtra,West,Consumer Durables,Large,A,60,SR013,2018-09-04,194.74
5998,C05999,Metro Solutions Works,Ahmedabad,Gujarat,West,Construction,Large,A,60,SR039,2018-05-30,61.49

##13. Sort customers by credit limit

In [61]:
customers.sort_values("credit_limit_lakh",ascending=False)

,customer_id,customer_name,city,state,region,industry,customer_size,segment,credit_days,sales_rep_id,created_date,credit_limit_lakh
2334,C02335,Trinity Works LLP,Bengaluru,Karnataka,South,Automotive,Enterprise,A+,75,SR016,2022-08-18,2796.73
2568,C02569,Om Industries Pvt Ltd,Pune,Maharashtra,West,General Engineering,Enterprise,A+,75,SR040,2020-04-03,2789.99
354,C00355,Sterling Solutions Private Limited,Delhi,Delhi,North,Fabrication,Enterprise,A+,75,SR007,2021-06-22,2788.11
390,C00391,Vertex Projects Industries,Mumbai,Maharashtra,West,Consumer Durables,Enterprise,A+,75,SR009,2021-09-18,2765.93
4677,C04678,Sterling Equipments Works,Pune,Maharashtra,West,Fabrication,Enterprise,A+,75,SR013,2024-08-12,2747.06
...,...,...,...,...,...,...,...,...,...,...,...,...
4348,C04349,Mahalaxmi Enterprises Industries,Delhi,Delhi,North,Industrial Machinery,Micro,D,15,SR033,2019-05-25,2.05
487,C00488,Trinity Systems Ltd,Mumbai,Maharashtra,West,Automotive,Micro,D,15,SR019,2019-03-27,2.04
2651,C02652,Bharat Solutions LLP,Pune,Maharashtra,West,Renewables,Micro,D,15,SR012,2023-07-29,2.02
3376,C03377,Fusion Fabricators LLP,Jaipur,Rajasthan,North,Renewables,Micro,D,15,SR006,2018-07-13,2.02
1440,C01441,Western Industries Pvt Ltd,Rajkot,Gujarat,West,Industrial Machinery,Micro,D,15,SR003,2023-04-23,2.01

##14. Find unique industries.

In [67]:
pd.DataFrame(customers["industry"].unique(),columns=["Industry"])

               Industry
0             Aerospace
1            Automotive
2            Electrical
3  Industrial Machinery
4          Construction
5   General Engineering
6            Renewables
7           Fabrication
8              Railways
9     Consumer Durables

##15. Count customers by region.

In [76]:
customers.groupby("region").size().reset_index().rename(columns={'region':'Region',0:'Total'})

    Region  Total
0  Central    747
1     East    143
2    North   1290
3    South    980
4     West   2840

##16. Calculate average credit days by size.

In [77]:
customers.head()

,customer_id,customer_name,city,state,region,industry,customer_size,segment,credit_days,sales_rep_id,created_date,credit_limit_lakh
0,C00001,Trinity Fasteners Works,Nashik,Maharashtra,West,Aerospace,Micro,D,15,SR029,2021-06-09,12.02
1,C00002,Nova Fasteners Ltd,Bengaluru,Karnataka,South,Automotive,Small,C,30,SR005,2021-10-10,151.83
2,C00003,Royal Equipments Works,Nashik,Maharashtra,West,Electrical,Small,C,30,SR029,2018-05-16,123.22
3,C00004,Universal Equipments LLP,Ahmedabad,Gujarat,West,Industrial Machinery,Micro,D,15,SR001,2018-10-25,72.55
4,C00005,Metro Equipments Works,Bhopal,Madhya Pradesh,Central,Construction,Small,C,30,SR036,2022-11-12,8.01

In [83]:
customers.groupby('customer_size')['credit_days'].mean().reset_index(name='Average Credit Days').sort_values('Average Credit Days',ascending=False)

  customer_size  Average Credit Days
0    Enterprise                 75.0
1         Large                 60.0
2        Medium                 45.0
4         Small                 30.0
3         Micro                 15.0

##17. Load products.

In [84]:
products =pd.read_csv(r"F:\Project Data Master\Asteron_Data_Lab_v1_Learner_Pack\raw\erp_products.csv")
products.head()

,product_id,product_name,category,material,diameter_mm,length_mm,primary_supplier_id,standard_cost,list_price,uom
0,P0001,Hex Bolts SS304 M8x50,Hex Bolts,SS304,8,50,S012,10.76,16.51,PCS
1,P0002,Special Fasteners SS304 M8x40,Special Fasteners,SS304,8,40,S068,4.73,6.09,PCS
2,P0003,Self Tapping Screws SS304 M8x25,Self Tapping Screws,SS304,8,25,S084,12.06,17.28,BOX
3,P0004,Hex Bolts MS M12x40,Hex Bolts,MS,12,40,S084,4.19,5.74,PCS
4,P0005,Special Fasteners MS M10x30,Special Fasteners,MS,10,30,S036,14.97,19.63,PCS

##18. Find products above a chosen price threshold.

In [92]:
products[products['list_price'] > 20].sort_values('list_price',ascending=False)

,product_id,product_name,category,material,diameter_mm,length_mm,primary_supplier_id,standard_cost,list_price,uom
790,P0791,Industrial Consumables Alloy Steel M6x10,Industrial Consumables,Alloy Steel,6,10,S073,66.10,101.58,PCS
613,P0614,Anchors MS M16x25,Anchors,MS,16,25,S063,73.67,98.48,PCS
42,P0043,Socket Screws SS316 M20x30,Socket Screws,SS316,20,30,S060,57.46,93.93,PCS
695,P0696,Socket Screws Alloy Steel M16x16,Socket Screws,Alloy Steel,16,16,S039,60.28,86.83,PCS
888,P0889,Cutting Tools Brass M10x40,Cutting Tools,Brass,10,40,S028,50.37,80.40,PCS
...,...,...,...,...,...,...,...,...,...,...
148,P0149,Nuts SS304 M20x30,Nuts,SS304,20,30,S059,13.97,20.22,PCS
944,P0945,Hex Bolts MS M24x25,Hex Bolts,MS,24,25,S055,12.71,20.22,PCS
402,P0403,Special Fasteners SS304 M10x25,Special Fasteners,SS304,10,25,S038,13.40,20.21,PCS
254,P0255,Anchors MS M10x50,Anchors,MS,10,50,S029,13.25,20.08,PCS
345,P0346,Special Fasteners MS M5x30,Special Fasteners,MS,5,30,S060,15.32,20.07,PCS

##19. Count products by category.

In [97]:
products.groupby('category').size().reset_index().rename(columns={'category':'Category',0:'No. Of Items'}).sort_values('No. Of Items')

                 Category  No. Of Items
1           Cutting Tools            58
8           Threaded Rods            68
5     Self Tapping Screws            75
0                 Anchors            75
3  Industrial Consumables            82
7       Special Fasteners            91
9                 Washers           101
4                    Nuts           116
6           Socket Screws           141
2               Hex Bolts           193

##20. Calculate average list price by category.

In [102]:
products.groupby('category')['list_price'].mean().reset_index(name='List Price Average')

                 category  List Price Average
0                 Anchors           17.011467
1           Cutting Tools           17.898793
2               Hex Bolts           17.404041
3  Industrial Consumables           16.691707
4                    Nuts           17.190948
5     Self Tapping Screws           14.287067
6           Socket Screws           16.366099
7       Special Fasteners           15.767582
8           Threaded Rods           18.535882
9                 Washers           18.127624