# Asteron Data Lab — Python/Pandas Q21–40
## Phase 2 — Data Cleaning

##21. Profile missing values across CRM accounts.

In [4]:
import pandas as pd
CRM_accounts=pd.read_csv(r"F:\Project Data Master\Asteron_Data_Lab_v1_Learner_Pack\raw\crm_accounts.csv")
CRM_accounts.head(10)

,crm_account_id,account_name,city,state,industry,owner_sales_rep_id,created_date,erp_customer_id
0,A00002,Nova Fasteners Ltd,Bengaluru,Karnataka,Automotive,SR005,2021-10-10,C00002
1,A00003,Royal Equipments Works,Nashik,Maharashtra,Electrical,SR029,2018-05-16,C00003
2,A00004,Universal Equipments LLP,Ahmedabad,Gujarat,Industrial Machinery,SR001,2018-10-25,C00004
3,A00005,Metro Equipments Works,Bhopal,Madhya Pradesh,Construction,SR036,2022-11-12,C00005
4,A00006,Sterling Systems Private Limited,Ahmedabad,Gujarat,Automotive,SR032,2022-05-21,C00006
5,A00007,Royal Tools Works,Ludhiana,Punjab,Industrial Machinery,SR030,2025-06-25,C00007
6,A00008,Galaxy Works Ltd,Pune,Maharashtra,Electrical,SR034,2019-02-28,C00008
7,A00008D,Galaxy Works Ltd,Pune,Maharashtra,Electrical,SR034,2019-02-28,NaN
8,A00009,VERTEX IND. LTD,Ludhiana,Punjab,Automotive,SR030,2026-03-18,C00009
9,A00010,Apex Enterprises Works,Mumbai,Maharashtra,General Engineering,SR041,2021-02-02,C00010

In [12]:
CRM_accounts['account_name'].isna().sum()

np.int64(0)

In [13]:
CRM_accounts.isna().sum()

crm_account_id          0
account_name            0
city                    0
state                   0
industry                0
owner_sales_rep_id      0
created_date            0
erp_customer_id       482
dtype: int64

##22. Find duplicate CRM account names.

In [27]:
repeat_account_name = CRM_accounts.groupby('account_name').size().reset_index(name='Name Repeat').sort_values('Name Repeat',ascending=False)
repeat_account_name[repeat_account_name['Name Repeat'] > 1]

                             account_name  Name Repeat
699                      Galaxy Works Ltd            7
2135       Sigma Manufacturing Industries            7
633                Galaxy Fabricators Ltd            7
2386          Trinity Fabricators Pvt Ltd            7
1978        Sai Solutions Private Limited            6
...                                   ...          ...
2926                    Zenith Works Ind.            2
2921                     Zenith Tools LLP            2
2888              Zenith Machines Pvt Ltd            2
2916  Zenith Technologies Private Limited            2
2910       Zenith Systems Private Limited            2

[1568 rows x 2 columns]

In [31]:
CRM_accounts[CRM_accounts['account_name'].duplicated(keep=False)].sort_values('account_name')

,crm_account_id,account_name,city,state,industry,owner_sales_rep_id,created_date,erp_customer_id
234,A00252,ACCURATE MACHINES LTD,Chennai,Tamil Nadu,Fabrication,SR016,2021-02-01,C00252
445,A00473,ACCURATE MACHINES LTD,Delhi,Delhi,Fabrication,SR006,2019-05-01,C00473
4049,A04320,Accurate Auto Parts Pvt Ltd,Ahmedabad,Gujarat,Construction,SR041,2024-09-17,C04320
3262,A03493,Accurate Auto Parts Pvt Ltd,Indore,Madhya Pradesh,Aerospace,SR020,2018-11-19,C03493
347,A00370,Accurate Auto Parts Pvt Ltd,Nagpur,Maharashtra,Industrial Machinery,SR036,2019-07-29,C00370
...,...,...,...,...,...,...,...,...
1355,A01447,Zenith Works Pvt Ltd,Faridabad,Haryana,Fabrication,SR037,2020-04-09,C01447
448,A00476,Zenith Works Pvt Ltd,Delhi,Delhi,Construction,SR044,2024-04-24,C00476
1499,A01602,Zenith Works Pvt Ltd,Nashik,Maharashtra,Construction,SR034,2025-11-07,C01602
3043,A03248,Zenith Works Pvt Ltd,Indore,Madhya Pradesh,Fabrication,SR024,2025-09-23,C03248
227,A00246,Zenith Works Pvt Ltd,Nagpur,Maharashtra,Automotive,SR035,2019-02-10,C00246

##23. Normalize whitespace in account names.

In [34]:
CRM_accounts['account_name']=CRM_accounts['account_name'].str.strip().str.replace(r'\s+',' ',regex=True)

In [35]:
CRM_accounts[['account_name']].head(20)

                            account_name
0                     Nova Fasteners Ltd
1                 Royal Equipments Works
2               Universal Equipments LLP
3                 Metro Equipments Works
4       Sterling Systems Private Limited
5                      Royal Tools Works
6                       Galaxy Works Ltd
7                       Galaxy Works Ltd
8                        VERTEX IND. LTD
9                 Apex Enterprises Works
10            Royal Fasteners Industries
11             Vardhman Auto Parts Works
12             Supreme Solutions Pvt Ltd
13             Royal Fabricators Pvt Ltd
14         Eastern Components Industries
15              SUPREME WORKS INDUSTRIES
16    Supreme Equipments Private Limited
17               Eastern Systems Pvt Ltd
18                Indus Technologies LLP
19  National Fabricators Private Limited

##24. Normalize capitalization.

In [41]:
CRM_accounts['accounts_name']=CRM_accounts['account_name'].str.title()
CRM_accounts.head(10)

,crm_account_id,account_name,city,state,industry,owner_sales_rep_id,created_date,erp_customer_id,accounts_name
0,A00002,Nova Fasteners Ltd,Bengaluru,Karnataka,Automotive,SR005,2021-10-10,C00002,Nova Fasteners Ltd
1,A00003,Royal Equipments Works,Nashik,Maharashtra,Electrical,SR029,2018-05-16,C00003,Royal Equipments Works
2,A00004,Universal Equipments LLP,Ahmedabad,Gujarat,Industrial Machinery,SR001,2018-10-25,C00004,Universal Equipments Llp
3,A00005,Metro Equipments Works,Bhopal,Madhya Pradesh,Construction,SR036,2022-11-12,C00005,Metro Equipments Works
4,A00006,Sterling Systems Private Limited,Ahmedabad,Gujarat,Automotive,SR032,2022-05-21,C00006,Sterling Systems Private Limited
5,A00007,Royal Tools Works,Ludhiana,Punjab,Industrial Machinery,SR030,2025-06-25,C00007,Royal Tools Works
6,A00008,Galaxy Works Ltd,Pune,Maharashtra,Electrical,SR034,2019-02-28,C00008,Galaxy Works Ltd
7,A00008D,Galaxy Works Ltd,Pune,Maharashtra,Electrical,SR034,2019-02-28,NaN,Galaxy Works Ltd
8,A00009,VERTEX IND. LTD,Ludhiana,Punjab,Automotive,SR030,2026-03-18,C00009,Vertex Ind. Ltd
9,A00010,Apex Enterprises Works,Mumbai,Maharashtra,General Engineering,SR041,2021-02-02,C00010,Apex Enterprises Works

In [42]:
CRM_accounts.drop(columns=['accounts_name'],inplace=True)

In [43]:
CRM_accounts['account_name']=CRM_accounts['account_name'].str.title()
CRM_accounts.head()

,crm_account_id,account_name,city,state,industry,owner_sales_rep_id,created_date,erp_customer_id
0,A00002,Nova Fasteners Ltd,Bengaluru,Karnataka,Automotive,SR005,2021-10-10,C00002
1,A00003,Royal Equipments Works,Nashik,Maharashtra,Electrical,SR029,2018-05-16,C00003
2,A00004,Universal Equipments Llp,Ahmedabad,Gujarat,Industrial Machinery,SR001,2018-10-25,C00004
3,A00005,Metro Equipments Works,Bhopal,Madhya Pradesh,Construction,SR036,2022-11-12,C00005
4,A00006,Sterling Systems Private Limited,Ahmedabad,Gujarat,Automotive,SR032,2022-05-21,C00006

##25. Compare ERP and CRM state labels.

In [47]:
customers = pd.read_csv(r"F:\Project Data Master\Asteron_Data_Lab_v1_Learner_Pack\raw\erp_customers.csv")
customers['state'].unique()

array(['Maharashtra', 'Karnataka', 'Gujarat', 'Madhya Pradesh', 'Punjab',
       'Delhi', 'Haryana', 'Tamil Nadu', 'Rajasthan', 'Telangana',
       'West Bengal'], dtype=object)

In [48]:
CRM_accounts['state'].unique()

array(['Karnataka', 'Maharashtra', 'Gujarat', 'Madhya Pradesh', 'Punjab',
       'Delhi', 'Haryana', 'Rajasthan', 'Telangana', 'Tamil Nadu',
       'West Bengal'], dtype=object)

In [49]:
set(customers['state'].unique()) - set(CRM_accounts['state'].unique())

set()

In [50]:
set(CRM_accounts['state'].unique()) - set(customers['state'].unique())

set()

##26. Standardize obvious state-label variants.

In [54]:
CRM_accounts['state'].unique()

array(['Karnataka', 'Maharashtra', 'Gujarat', 'Madhya Pradesh', 'Punjab',
       'Delhi', 'Haryana', 'Rajasthan', 'Telangana', 'Tamil Nadu',
       'West Bengal'], dtype=object)

In [53]:
CRM_accounts['state'] = CRM_accounts['state'].str.strip().str.replace(r'\s+',' ',regex=True)

In [56]:
CRM_accounts['state'].value_counts().reset_index(name='total no.')

             state  total no.
0      Maharashtra       2227
1          Gujarat        773
2          Haryana        476
3       Tamil Nadu        411
4   Madhya Pradesh        384
5            Delhi        351
6        Karnataka        287
7        Telangana        230
8           Punjab        190
9        Rajasthan        187
10     West Bengal        137

##27. Find blank ERP customer IDs in CRM.

In [63]:
CRM_accounts[CRM_accounts['erp_customer_id'].isna()].

,crm_account_id,account_name,city,state,industry,owner_sales_rep_id,created_date,erp_customer_id
7,A00008D,Galaxy Works Ltd,Pune,Maharashtra,Electrical,SR034,2019-02-28,NaN
26,A00029D,Nova Tools Pvt Ltd,Gurugram,Haryana,Industrial Machinery,SR006,2018-03-31,NaN
39,A00043,National Enterprises Pvt Ltd,Coimbatore,Tamil Nadu,Industrial Machinery,SR016,2023-05-23,NaN
62,A00068D,Western Technologies Llp,Ahmedabad,Gujarat,Renewables,SR012,2023-07-27,NaN
66,A00073,Supreme Solutions Industries,Ludhiana,Punjab,Electrical,SR010,2018-12-16,NaN
...,...,...,...,...,...,...,...,...
5612,A05958,Prime Machines Works,Kolkata,West Bengal,Construction,SR001,2023-09-25,NaN
5623,A05970,Supreme Solutions Llp,Ludhiana,Punjab,Automotive,SR025,2018-02-26,NaN
5636,A05985D,Om Engineering Works,Rajkot,Gujarat,General Engineering,SR026,2018-08-22,NaN
5641,A05989D,Bharat Auto Parts Pvt Ltd,Pune,Maharashtra,Automotive,SR031,2019-05-21,NaN
5651,A05999D,Metro Solutions Works,Ahmedabad,Gujarat,Construction,SR039,2018-05-30,NaN

##28. Find invalid ERP IDs.

In [65]:
CRM_accounts['erp_customer_id'].unique()

array(['C00002', 'C00003', 'C00004', ..., 'C05998', 'C05999', 'C06000'],
      dtype=object)

In [66]:
customers.head(10)

,customer_id,customer_name,city,state,region,industry,customer_size,segment,credit_days,sales_rep_id,created_date,credit_limit_lakh
0,C00001,Trinity Fasteners Works,Nashik,Maharashtra,West,Aerospace,Micro,D,15,SR029,2021-06-09,12.02
1,C00002,Nova Fasteners Ltd,Bengaluru,Karnataka,South,Automotive,Small,C,30,SR005,2021-10-10,151.83
2,C00003,Royal Equipments Works,Nashik,Maharashtra,West,Electrical,Small,C,30,SR029,2018-05-16,123.22
3,C00004,Universal Equipments LLP,Ahmedabad,Gujarat,West,Industrial Machinery,Micro,D,15,SR001,2018-10-25,72.55
4,C00005,Metro Equipments Works,Bhopal,Madhya Pradesh,Central,Construction,Small,C,30,SR036,2022-11-12,8.01
5,C00006,Sterling Systems Private Limited,Ahmedabad,Gujarat,West,Automotive,Large,A,60,SR032,2022-05-21,153.75
6,C00007,Royal Tools Works,Ludhiana,Punjab,North,Industrial Machinery,Medium,B,45,SR030,2025-06-25,165.82
7,C00008,Galaxy Works Ltd,Pune,Maharashtra,West,Electrical,Small,C,30,SR034,2019-02-28,63.05
8,C00009,Vertex Industries Ltd,Ludhiana,Punjab,North,Automotive,Medium,B,45,SR030,2026-03-18,107.97
9,C00010,Apex Enterprises Works,Mumbai,Maharashtra,West,General Engineering,Medium,B,45,SR041,2021-02-02,271.00

In [67]:
set(CRM_accounts['erp_customer_id'].dropna())-set(customers['customer_id'])

set()

In [70]:
CRM_accounts[CRM_accounts['erp_customer_id'].notna()&~CRM_accounts['erp_customer_id'].isin(customers['customer_id'])]

Empty DataFrame
Columns: [crm_account_id, account_name, city, state, industry, owner_sales_rep_id, created_date, erp_customer_id]
Index: []

##29. Detect zero-quantity order lines.

In [77]:
erp_order_items = pd.read_csv(r"F:\Project Data Master\Asteron_Data_Lab_v1_Learner_Pack\raw\erp_order_items.csv")
erp_order_items[erp_order_items['quantity'] == 0]

,order_item_id,order_id,product_id,quantity,unit_price,unit_cost_at_order,discount_pct,uom
521,OI0000167-01,O0000167,P0929,0,16.02,12.29,0.1113,PCS
2712,OI0000826-01,O0000826,P0672,0,6.19,4.62,0.1118,BOX
4435,OI0001350-02,O0001350,P0157,0,27.17,22.25,0.0673,PCS
6044,OI0001862-04,O0001862,P0522,0,20.85,16.52,0.1382,PCS
7563,OI0002338-01,O0002338,P0095,0,10.27,9.66,0.1592,PCS
...,...,...,...,...,...,...,...,...
140321,OI0043964-01,O0043964,P0893,0,7.19,5.71,0.1353,100PCS
140952,OI0044163-02,O0044163,P0408,0,5.45,3.85,0.1210,PCS
141763,OI0044425-02,O0044425,P0663,0,12.54,7.78,0.0213,PCS
141915,OI0044475-03,O0044475,P0734,0,3.94,3.53,0.1479,BOX
142425,OI0044629-02,O0044629,P0567,0,16.83,15.62,0.1314,PCS

In [78]:
erp_order_items.head()

,order_item_id,order_id,product_id,quantity,unit_price,unit_cost_at_order,discount_pct,uom
0,OI0000001-01,O0000001,P0672,2925,5.56,4.62,0.2027,BOX
1,OI0000001-02,O0000001,P0439,619,1.47,1.19,0.1649,PCS
2,OI0000001-03,O0000001,P0683,210,12.44,9.99,0.2027,PCS
3,OI0000001-04,O0000001,P0860,343,2.68,2.10,0.1600,PCS
4,OI0000001-05,O0000001,P0765,5133,6.93,6.71,0.2014,PCS

##30. Detect extreme unit prices.

In [79]:
erp_order_items.head()

,order_item_id,order_id,product_id,quantity,unit_price,unit_cost_at_order,discount_pct,uom
0,OI0000001-01,O0000001,P0672,2925,5.56,4.62,0.2027,BOX
1,OI0000001-02,O0000001,P0439,619,1.47,1.19,0.1649,PCS
2,OI0000001-03,O0000001,P0683,210,12.44,9.99,0.2027,PCS
3,OI0000001-04,O0000001,P0860,343,2.68,2.10,0.1600,PCS
4,OI0000001-05,O0000001,P0765,5133,6.93,6.71,0.2014,PCS

In [81]:
erp_order_items.sort_values('unit_price',ascending=False)

,order_item_id,order_id,product_id,quantity,unit_price,unit_cost_at_order,discount_pct,uom
84013,OI0026341-04,O0026341,P0812,471,6050.00,49.52,0.1727,PCS
11163,OI0003476-03,O0003476,P0622,2211,6036.00,53.44,0.1356,PCS
130511,OI0040897-01,O0040897,P0926,673,4925.00,40.06,0.0854,PCS
123125,OI0038567-03,O0038567,P0996,197,4838.00,31.98,0.0637,PCS
109114,OI0034167-04,O0034167,P0767,121,4795.00,41.09,0.0786,PCS
...,...,...,...,...,...,...,...,...
111490,OI0034910-05,O0034910,P0867,478,0.70,0.68,0.2006,PCS
105346,OI0032986-01,O0032986,P0867,96,0.69,0.68,0.2012,PCS
137797,OI0043158-04,O0043158,P0867,555,0.68,0.68,0.2223,PCS
83811,OI0026282-02,O0026282,P0867,476,0.68,0.68,0.2191,PCS
124149,OI0038884-01,O0038884,P0867,316,0.65,0.68,0.2556,PCS

In [82]:
erp_order_items['unit_price'].describe()

count    143569.000000
mean         15.636541
std          62.012966
min           0.650000
25%           6.180000
50%          10.270000
75%          18.560000
max        6050.000000
Name: unit_price, dtype: float64

In [85]:
erp_order_items[erp_order_items['unit_price']>1000].sort_values('unit_price',ascending=False)

,order_item_id,order_id,product_id,quantity,unit_price,unit_cost_at_order,discount_pct,uom
84013,OI0026341-04,O0026341,P0812,471,6050.0,49.52,0.1727,PCS
11163,OI0003476-03,O0003476,P0622,2211,6036.0,53.44,0.1356,PCS
130511,OI0040897-01,O0040897,P0926,673,4925.0,40.06,0.0854,PCS
123125,OI0038567-03,O0038567,P0996,197,4838.0,31.98,0.0637,PCS
109114,OI0034167-04,O0034167,P0767,121,4795.0,41.09,0.0786,PCS
...,...,...,...,...,...,...,...,...
31642,OI0009916-03,O0009916,P0817,309,1043.0,9.28,0.1172,PCS
124730,OI0039065-03,O0039065,P0804,323,1041.0,8.58,0.1117,PCS
135676,OI0042504-03,O0042504,P0747,221,1038.0,8.73,0.1758,PCS
111821,OI0035011-01,O0035011,P0253,327,1031.0,9.26,0.1214,PCS
37108,OI0011664-02,O0011664,P0747,321,1012.0,8.73,0.1965,PCS

##31. Calculate product-level price distributions.

In [98]:
erp_order_items[['product_id','unit_price']].groupby('product_id').describe()

           unit_price                                                          \
                count       mean         std    min      25%     50%      75%
product_id
P0001           506.0  17.461640   65.463135  12.66  14.0225  14.530  15.1400
P0002            21.0   5.338095    0.281614   4.84   5.1800   5.220   5.5500
P0003           112.0  15.155446    0.841927  13.45  14.6350  15.055  15.7350
P0004           115.0   5.100696    0.273241   4.48   4.8950   5.090   5.2900
P0005            14.0  17.047857    1.163815  15.34  16.1350  17.075  17.8825
...               ...        ...         ...    ...      ...     ...      ...
P0996          1134.0  53.708810  194.229045  38.91  43.6925  45.490  47.5900
P0997           157.0  22.071975    1.180435  19.71  21.2100  22.030  22.9800
P0998            34.0   7.299706    0.505626   6.19   6.8950   7.370   7.6625
P0999            53.0   7.441887    0.383391   6.36   7.2300   7.490   7.6900
P1000           135.0  16.953333    0.892027  14.62  16.4100  16.930  17.5750


                max
product_id
P0001       1487.00
P0002          5.81
P0003         16.90
P0004          5.62
P0005         18.99
...             ...
P0996       4838.00
P0997         24.34
P0998          8.16
P0999          8.14
P1000         18.68

[1000 rows x 8 columns]

##32. Use IQR to flag price outliers.

In [110]:
IQR_cal = erp_order_items[['product_id','unit_price']].groupby('product_id').describe()
IQR_cal.head(10)
IQR_cal['IQR'] = IQR_cal[('unit_price','75%')]-IQR_cal[('unit_price','25%')]
IQR_cal['upper']=IQR_cal[('unit_price','75%')]+(1.5*IQR_cal['IQR'])
IQR_cal['lower']=IQR_cal[('unit_price','25%')]-(1.5*IQR_cal['IQR'])
IQR_cal.head(10)

           unit_price                                                         \
                count       mean        std    min      25%     50%      75%
product_id
P0001           506.0  17.461640  65.463135  12.66  14.0225  14.530  15.1400
P0002            21.0   5.338095   0.281614   4.84   5.1800   5.220   5.5500
P0003           112.0  15.155446   0.841927  13.45  14.6350  15.055  15.7350
P0004           115.0   5.100696   0.273241   4.48   4.8950   5.090   5.2900
P0005            14.0  17.047857   1.163815  15.34  16.1350  17.075  17.8825
P0006            17.0  15.831765   0.922505  13.97  15.0800  15.800  16.5800
P0007            13.0   8.003077   0.547180   7.20   7.6100   8.260   8.3800
P0008           314.0   8.462930  38.642696   5.09   6.0200   6.260   6.5850
P0009            54.0  19.615556   1.075169  17.33  18.6800  19.725  20.3700
P0010            63.0  17.499206  82.766121   6.18   6.7700   7.130   7.3200

                        IQR     upper     lower
                max
product_id
P0001       1487.00  1.1175  16.81625  12.34625
P0002          5.81  0.3700   6.10500   4.62500
P0003         16.90  1.1000  17.38500  12.98500
P0004          5.62  0.3950   5.88250   4.30250
P0005         18.99  1.7475  20.50375  13.51375
P0006         17.11  1.5000  18.83000  12.83000
P0007          8.87  0.7700   9.53500   6.45500
P0008        691.00  0.5650   7.43250   5.17250
P0009         21.67  1.6900  22.90500  16.14500
P0010        664.00  0.5500   8.14500   5.94500

In [115]:
IQR_cal.reset_index(inplace=True)

In [116]:
IQR_cal.columns

MultiIndex([(     'index',      ''),
            ('product_id',      ''),
            ('unit_price', 'count'),
            ('unit_price',  'mean'),
            ('unit_price',   'std'),
            ('unit_price',   'min'),
            ('unit_price',   '25%'),
            ('unit_price',   '50%'),
            ('unit_price',   '75%'),
            ('unit_price',   'max'),
            (       'IQR',      ''),
            (     'upper',      ''),
            (     'lower',      '')],
           )

In [117]:
bounds = IQR_cal[
    [('product_id', ''), ('upper', ''), ('lower', '')]
].copy()

In [118]:
bounds.head(10)

  product_id     upper     lower

0      P0001  16.81625  12.34625
1      P0002   6.10500   4.62500
2      P0003  17.38500  12.98500
3      P0004   5.88250   4.30250
4      P0005  20.50375  13.51375
5      P0006  18.83000  12.83000
6      P0007   9.53500   6.45500
7      P0008   7.43250   5.17250
8      P0009  22.90500  16.14500
9      P0010   8.14500   5.94500

In [120]:
bounds.columns = ['product_id', 'upper', 'lower']

In [122]:
bounds.head()

  product_id     upper     lower
0      P0001  16.81625  12.34625
1      P0002   6.10500   4.62500
2      P0003  17.38500  12.98500
3      P0004   5.88250   4.30250
4      P0005  20.50375  13.51375

In [125]:
erp_order_items = erp_order_items.merge(bounds,on='product_id',how='left')

In [126]:
erp_order_items[['product_id', 'unit_price', 'lower', 'upper']].head()

  product_id  unit_price     lower     upper
0      P0672        5.56   5.16000   7.16000
1      P0439        1.47   1.29500   1.81500
2      P0683       12.44  11.58750  15.90750
3      P0860        2.68   2.23750   3.41750
4      P0765        6.93   6.38875   8.89875

In [127]:
outliers = erp_order_items[
    (erp_order_items['unit_price'] < erp_order_items['lower']) |
    (erp_order_items['unit_price'] > erp_order_items['upper'])
]

In [128]:
outliers.head(20)

,order_item_id,order_id,product_id,quantity,unit_price,unit_cost_at_order,discount_pct,uom,upper,lower
96,OI0000031-01,O0000031,P0410,2163,5.57,4.47,0.2178,PCS,6.97250,5.59250
679,OI0000216-03,O0000216,P0066,1908,3417.00,33.64,0.2221,PCS,44.84375,32.61375
1220,OI0000380-01,O0000380,P0494,936,24.36,22.40,0.2216,PCS,30.26625,24.89625
1248,OI0000389-02,O0000389,P0292,241,13.94,13.67,0.2073,PCS,17.63500,14.07500
1404,OI0000429-06,O0000429,P0719,526,6.94,5.98,0.2612,PCS,9.65250,6.95250
1428,OI0000437-01,O0000437,P0809,87,5.11,4.19,0.0286,PCS,4.98500,4.06500
1445,OI0000442-01,O0000442,P0602,101,26.03,22.60,0.2899,PCS,37.53750,27.41750
2667,OI0000810-04,O0000810,P0576,848,9.85,9.47,0.1868,PCS,11.73875,9.86875
3372,OI0001035-02,O0001035,P0536,405,9.52,9.52,0.2953,PCS,13.40000,10.18000
3461,OI0001064-04,O0001064,P0587,199,30.19,29.40,0.2226,BOX,38.12500,30.74500
4089,OI0001250-04,O0001250,P0823,127,24.03,15.65,0.0206,PCS,23.97125,19.04125
4941,OI0001510-02,O0001510,P0761,119,1110.00,10.29,0.1365,PCS,13.01500,9.69500
5083,OI0001556-04,O0001556,P0895,171,1850.00,16.74,0.1441,PCS,22.71125,15.64125
5338,OI0001642-01,O0001642,P0150,499,1438.00,13.38,0.1297,PCS,16.94125,12.27125
5478,OI0001684-02,O0001684,P0537,302,1.67,1.46,0.2837,PCS,2.40625,1.69625
5479,OI0001684-03,O0001684,P0099,159,29.87,29.17,0.2992,PCS,43.50000,31.62000
5948,OI0001829-01,O0001829,P0394,157,32.55,28.57,0.2321,BOX,40.96500,33.72500
7044,OI0002176-01,O0002176,P0920,191,324.00,2.94,0.1231,PCS,3.82750,2.72750
7303,OI0002254-02,O0002254,P0945,105,14.53,12.71,0.2814,PCS,20.57500,15.09500
7411,OI0002287-02,O0002287,P0400,27,13.08,9.36,0.0407,PCS,12.84500,11.52500

##33. Compare suspicious prices against product medians.

In [135]:
bounds['median'] = IQR_cal[('unit_price','50%')]
bounds.head()

  product_id     upper     lower  median
0      P0001  16.81625  12.34625  14.530
1      P0002   6.10500   4.62500   5.220
2      P0003  17.38500  12.98500  15.055
3      P0004   5.88250   4.30250   5.090
4      P0005  20.50375  13.51375  17.075

In [141]:
erp_order_items = erp_order_items.merge(bounds[['product_id','median']],on='product_id',how='left')

In [142]:
erp_order_items.head()

,order_item_id,order_id,product_id,quantity,unit_price,unit_cost_at_order,discount_pct,uom,upper,lower,median
0,OI0000001-01,O0000001,P0672,2925,5.56,4.62,0.2027,BOX,7.16000,5.16000,6.16
1,OI0000001-02,O0000001,P0439,619,1.47,1.19,0.1649,PCS,1.81500,1.29500,1.55
2,OI0000001-03,O0000001,P0683,210,12.44,9.99,0.2027,PCS,15.90750,11.58750,13.81
3,OI0000001-04,O0000001,P0860,343,2.68,2.10,0.1600,PCS,3.41750,2.23750,2.82
4,OI0000001-05,O0000001,P0765,5133,6.93,6.71,0.2014,PCS,8.89875,6.38875,7.65

In [144]:
erp_order_items['Price vs Median'] = (erp_order_items['unit_price']/erp_order_items['median'])

In [145]:
erp_order_items.head()

,order_item_id,order_id,product_id,quantity,unit_price,unit_cost_at_order,discount_pct,uom,upper,lower,median,Price vs Median
0,OI0000001-01,O0000001,P0672,2925,5.56,4.62,0.2027,BOX,7.16000,5.16000,6.16,0.902597
1,OI0000001-02,O0000001,P0439,619,1.47,1.19,0.1649,PCS,1.81500,1.29500,1.55,0.948387
2,OI0000001-03,O0000001,P0683,210,12.44,9.99,0.2027,PCS,15.90750,11.58750,13.81,0.900797
3,OI0000001-04,O0000001,P0860,343,2.68,2.10,0.1600,PCS,3.41750,2.23750,2.82,0.950355
4,OI0000001-05,O0000001,P0765,5133,6.93,6.71,0.2014,PCS,8.89875,6.38875,7.65,0.905882

In [150]:
erp_order_items['outlier'] = ((erp_order_items['unit_price']>erp_order_items['upper']) | (erp_order_items['unit_price']<erp_order_items['lower']))

In [155]:
erp_order_items.value_counts('outlier')

outlier
False    143132
True        437
Name: count, dtype: int64

In [162]:
erp_order_items[erp_order_items['outlier']][['product_id','unit_price','median','Price vs Median','outlier']].sort_values('Price vs Median',ascending=False)

       product_id  unit_price  median  Price vs Median  outlier
89494       P0363     2926.00  26.095       112.128760     True
105318      P0978      826.00   7.435       111.096167     True
24978       P0208     1209.00  10.950       110.410959     True
85503       P0008      691.00   6.260       110.383387     True
113301      P0700      888.00   8.050       110.310559     True
...           ...         ...     ...              ...      ...
59610       P0195        6.78   8.580         0.790210     True
5479        P0099       29.87  37.810         0.790003     True
33256       P0150       11.46  14.610         0.784394     True
84251       P0866        6.73   8.630         0.779838     True
90498       P0507        4.02   5.190         0.774566     True

[437 rows x 5 columns]

##34. Find inconsistent UOM values.

In [184]:
multiple_uom = erp_order_items.groupby('product_id')['uom'].nunique().reset_index()
multiple_uom.sort_values('uom',ascending=False)

    product_id  uom
999      P1000    1
0        P0001    1
1        P0002    1
2        P0003    1
3        P0004    1
..         ...  ...
12       P0013    1
11       P0012    1
10       P0011    1
9        P0010    1
8        P0009    1

[1000 rows x 2 columns]

In [186]:
multiple_uom[multiple_uom['uom']>1]

Empty DataFrame
Columns: [product_id, uom]
Index: []

In [195]:
products_100pcs = erp_order_items[erp_order_items['uom'] == '100PCS']['product_id']
products_100pcs.head()

17     P0495
47     P0662
77     P0251
88     P0918
104    P0273
Name: product_id, dtype: object

In [200]:
erp_order_items[erp_order_items['product_id'].isin(products_100pcs)]['uom'].unique()

array(['100PCS'], dtype=object)

##35. Validate invoice subtotal + tax against total.

In [202]:
finance_invoices=pd.read_csv(r"F:\Project Data Master\Asteron_Data_Lab_v1_Learner_Pack\raw\finance_invoices.csv")
finance_invoices.head()

,invoice_id,order_id,customer_id,invoice_date,subtotal,tax_amount,invoice_total,invoice_status
0,INV0000001,O0000001,C05751,2021-05-05,56276.26,10129.73,66405.99,Posted
1,INV0000002,O0000002,C03324,2025-09-07,1638.79,294.98,1933.77,Posted
2,INV0000003,O0000003,C01574,2021-09-10,9731.60,1751.69,11483.29,Posted
3,INV0000004,O0000004,C02311,2024-12-26,6863.98,1235.52,8099.50,Posted
4,INV0000005,O0000005,C03788,2024-12-15,33214.74,5978.65,39193.39,Posted

In [213]:
finance_invoices['tally'] = finance_invoices['subtotal']+finance_invoices['tax_amount']== finance_invoices['invoice_total']
finance_invoices.head(10)

,invoice_id,order_id,customer_id,invoice_date,subtotal,tax_amount,invoice_total,invoice_status,tally
0,INV0000001,O0000001,C05751,2021-05-05,56276.26,10129.73,66405.99,Posted,True
1,INV0000002,O0000002,C03324,2025-09-07,1638.79,294.98,1933.77,Posted,True
2,INV0000003,O0000003,C01574,2021-09-10,9731.60,1751.69,11483.29,Posted,True
3,INV0000004,O0000004,C02311,2024-12-26,6863.98,1235.52,8099.50,Posted,True
4,INV0000005,O0000005,C03788,2024-12-15,33214.74,5978.65,39193.39,Posted,True
5,INV0000006,O0000006,C05485,2021-02-27,2137.61,384.77,2522.38,Posted,True
6,INV0000007,O0000007,C00833,2026-02-23,103318.32,18597.30,121915.62,Posted,False
7,INV0000008,O0000008,C00677,2024-11-17,6486.75,1167.62,7654.37,Posted,True
8,INV0000009,O0000010,C01732,2025-12-20,7190.14,1294.23,8484.37,Posted,True
9,INV0000010,O0000011,C05270,2023-04-14,100.80,18.14,118.94,Posted,True

In [216]:
finance_invoices['tally'].value_counts()

tally
True     32048
False     9118
Name: count, dtype: int64

In [217]:
finance_invoices[finance_invoices['tally']==False]

,invoice_id,order_id,customer_id,invoice_date,subtotal,tax_amount,invoice_total,invoice_status,tally
6,INV0000007,O0000007,C00833,2026-02-23,103318.32,18597.30,121915.62,Posted,False
13,INV0000014,O0000015,C05104,2023-08-08,6109.69,1099.74,7209.43,Posted,False
16,INV0000017,O0000018,C02336,2024-03-01,1829.41,329.29,2158.70,Posted,False
21,INV0000022,O0000025,C04374,2023-02-16,23475.08,4225.51,27700.59,Posted,False
24,INV0000025,O0000028,C02739,2023-03-22,83359.50,15004.71,98364.21,Posted,False
...,...,...,...,...,...,...,...,...,...
41136,INV0041137,O0044968,C04877,2024-05-03,14341.38,2581.45,16922.83,Posted,False
41150,INV0041151,O0044984,C01463,2023-01-19,34478.49,6206.13,40684.62,Posted,False
41161,INV0041162,O0044996,C05077,2023-01-19,2760.34,496.86,3257.20,Posted,False
41164,INV0041165,O0044999,C05982,2023-05-19,29115.78,5240.84,34356.62,Posted,False
41165,INV0041166,O0045000,C03918,2022-06-03,4298.22,773.68,5071.90,Posted,False

In [221]:
finance_invoices['of by'] = (finance_invoices['invoice_total']-finance_invoices['subtotal']-finance_invoices['tax_amount']).round(2)

In [224]:
finance_invoices.sort_values('of by',ascending=True)

,invoice_id,order_id,customer_id,invoice_date,subtotal,tax_amount,invoice_total,invoice_status,tally,of by
24090,INV0024091,O0026256,C01805,2023-09-17,75005.27,13500.95,75005.27,Posted,False,-13500.95
23415,INV0023416,O0025531,C01335,2026-02-27,69682.58,12542.86,69682.58,Posted,False,-12542.86
37704,INV0037705,O0041216,C00349,2026-05-23,67904.31,12222.78,67904.31,Posted,False,-12222.78
9310,INV0009311,O0010135,C05368,2022-04-18,60878.23,10958.08,60878.23,Posted,False,-10958.08
6599,INV0006600,O0007201,C03306,2026-06-28,45287.84,8151.81,45287.84,Posted,False,-8151.81
...,...,...,...,...,...,...,...,...,...,...
41162,INV0041163,O0044997,C03926,2024-02-27,6306.97,1135.25,7442.22,Reversed,True,0.00
41163,INV0041164,O0044998,C01761,2022-03-08,6854.14,1233.75,8087.89,Posted,True,0.00
41164,INV0041165,O0044999,C05982,2023-05-19,29115.78,5240.84,34356.62,Posted,False,0.00
41165,INV0041166,O0045000,C03918,2022-06-03,4298.22,773.68,5071.90,Posted,False,-0.00
0,INV0000001,O0000001,C05751,2021-05-05,56276.26,10129.73,66405.99,Posted,True,0.00

In [234]:
finance_invoices[finance_invoices['of by'] != 0][
    ['invoice_total', 'subtotal', 'tax_amount', 'of by']
].sort_values('of by')

       invoice_total  subtotal  tax_amount     of by
24090       75005.27  75005.27    13500.95 -13500.95
23415       69682.58  69682.58    12542.86 -12542.86
37704       67904.31  67904.31    12222.78 -12222.78
9310        60878.23  60878.23    10958.08 -10958.08
6599        45287.84  45287.84     8151.81  -8151.81
...              ...       ...         ...       ...
30405         567.82    567.82      102.21   -102.21
40049         414.75    414.75       74.66    -74.66
15817         360.75    360.75       64.93    -64.93
454           235.20    235.20       42.34    -42.34
25703         190.80    190.80       34.34    -34.34

[79 rows x 4 columns]

In [235]:
finance_invoices.rename(columns={'of by':'off_by'},inplace=True)

In [236]:
finance_invoices.head()

,invoice_id,order_id,customer_id,invoice_date,subtotal,tax_amount,invoice_total,invoice_status,tally,off_by
0,INV0000001,O0000001,C05751,2021-05-05,56276.26,10129.73,66405.99,Posted,True,0.0
1,INV0000002,O0000002,C03324,2025-09-07,1638.79,294.98,1933.77,Posted,True,0.0
2,INV0000003,O0000003,C01574,2021-09-10,9731.60,1751.69,11483.29,Posted,True,0.0
3,INV0000004,O0000004,C02311,2024-12-26,6863.98,1235.52,8099.50,Posted,True,0.0
4,INV0000005,O0000005,C03788,2024-12-15,33214.74,5978.65,39193.39,Posted,True,0.0

In [237]:
finance_invoices.rename(columns={'tally':'cal_is_valid'},inplace=True)

In [238]:
finance_invoices.head()

,invoice_id,order_id,customer_id,invoice_date,subtotal,tax_amount,invoice_total,invoice_status,cal_is_valid,off_by
0,INV0000001,O0000001,C05751,2021-05-05,56276.26,10129.73,66405.99,Posted,True,0.0
1,INV0000002,O0000002,C03324,2025-09-07,1638.79,294.98,1933.77,Posted,True,0.0
2,INV0000003,O0000003,C01574,2021-09-10,9731.60,1751.69,11483.29,Posted,True,0.0
3,INV0000004,O0000004,C02311,2024-12-26,6863.98,1235.52,8099.50,Posted,True,0.0
4,INV0000005,O0000005,C03788,2024-12-15,33214.74,5978.65,39193.39,Posted,True,0.0

##36. Flag reversed invoices.

In [245]:
finance_invoices['invoice_flag'] =  finance_invoices['invoice_status']=='Reversed'

In [248]:
finance_invoices[['invoice_status','invoice_flag']]

      invoice_status  invoice_flag
0             Posted         False
1             Posted         False
2             Posted         False
3             Posted         False
4             Posted         False
...              ...           ...
41161         Posted         False
41162       Reversed          True
41163         Posted         False
41164         Posted         False
41165         Posted         False

[41166 rows x 2 columns]

In [251]:
finance_invoices.rename(columns={'invoice_flag':'is_reversed'},inplace=True)

In [252]:
finance_invoices.head()

,invoice_id,order_id,customer_id,invoice_date,subtotal,tax_amount,invoice_total,invoice_status,cal_is_valid,off_by,is_reversed
0,INV0000001,O0000001,C05751,2021-05-05,56276.26,10129.73,66405.99,Posted,True,0.0,False
1,INV0000002,O0000002,C03324,2025-09-07,1638.79,294.98,1933.77,Posted,True,0.0,False
2,INV0000003,O0000003,C01574,2021-09-10,9731.60,1751.69,11483.29,Posted,True,0.0,False
3,INV0000004,O0000004,C02311,2024-12-26,6863.98,1235.52,8099.50,Posted,True,0.0,False
4,INV0000005,O0000005,C03788,2024-12-15,33214.74,5978.65,39193.39,Posted,True,0.0,False

##37. Detect duplicate rows.

In [256]:
finance_invoices.duplicated(subset=['invoice_id', 'order_id', 'invoice_date']).unique()

array([False])

In [257]:
finance_invoices[finance_invoices.duplicated()]

Empty DataFrame
Columns: [invoice_id, order_id, customer_id, invoice_date, subtotal, tax_amount, invoice_total, invoice_status, cal_is_valid, off_by, is_reversed]
Index: []

##38. Create a reusable data-quality report.

In [259]:
def data_quality_report(df):
    report = {
        'total_rows': len(df),
        'duplicate_rows': df.duplicated().sum(),
        'missing_values': df.isna().sum().sum(),
        'invalid_invoice_totals': (
            (df['subtotal'] + df['tax_amount']).round(2)
            != df['invoice_total'].round(2)
        ).sum(),
        'reversed_invoices': (
            df['invoice_status'] == 'Reversed'
        ).sum(),
        'duplicate_invoice_keys': df.duplicated(
            subset=['invoice_id', 'order_id', 'invoice_date']
        ).sum()
    }

    return pd.DataFrame(
        report.items(),
        columns=['check', 'count']
    )

In [260]:
data_quality_report(finance_invoices)

                    check  count
0              total_rows  41166
1          duplicate_rows      0
2          missing_values      0
3  invalid_invoice_totals     79
4       reversed_invoices    828
5  duplicate_invoice_keys      0

##39. Export flagged records to CSV.

In [280]:
flagged_record = finance_invoices[finance_invoices['off_by'] != 0].sort_values('off_by',ascending=True)
flagged_record.to_csv(r"F:\Project Data Master\Asteron_Data_Lab_v1_Learner_Pack\raw\flagged_records.csv",index=False)

In [281]:
flagged_record =pd.read_csv(r"F:\Project Data Master\Asteron_Data_Lab_v1_Learner_Pack\raw\flagged_records.csv")
flagged_record.head(10)

,invoice_id,order_id,customer_id,invoice_date,subtotal,tax_amount,invoice_total,invoice_status,cal_is_valid,off_by,is_reversed
0,INV0024091,O0026256,C01805,2023-09-17,75005.27,13500.95,75005.27,Posted,False,-13500.95,False
1,INV0023416,O0025531,C01335,2026-02-27,69682.58,12542.86,69682.58,Posted,False,-12542.86,False
2,INV0037705,O0041216,C00349,2026-05-23,67904.31,12222.78,67904.31,Posted,False,-12222.78,False
3,INV0009311,O0010135,C05368,2022-04-18,60878.23,10958.08,60878.23,Posted,False,-10958.08,False
4,INV0006600,O0007201,C03306,2026-06-28,45287.84,8151.81,45287.84,Posted,False,-8151.81,False
5,INV0022447,O0024481,C02366,2022-04-12,44343.30,7981.79,44343.30,Posted,False,-7981.79,False
6,INV0024323,O0026514,C00168,2025-12-10,36472.91,6565.12,36472.91,Posted,False,-6565.12,False
7,INV0016462,O0017967,C05544,2022-07-11,31616.17,5690.91,31616.17,Posted,False,-5690.91,False
8,INV0029849,O0032614,C02559,2026-01-25,31490.36,5668.26,31490.36,Posted,False,-5668.26,False
9,INV0001594,O0001741,C05035,2022-01-04,27288.15,4911.87,27288.15,Posted,False,-4911.87,False

##40. Write functions for common validation checks.

In [311]:
finance_invoices = pd.read_csv(
    r"F:\Project Data Master\Asteron_Data_Lab_v1_Learner_Pack\raw\finance_invoices.csv"
)

In [312]:
finance_invoices.head()

,invoice_id,order_id,customer_id,invoice_date,subtotal,tax_amount,invoice_total,invoice_status
0,INV0000001,O0000001,C05751,2021-05-05,56276.26,10129.73,66405.99,Posted
1,INV0000002,O0000002,C03324,2025-09-07,1638.79,294.98,1933.77,Posted
2,INV0000003,O0000003,C01574,2021-09-10,9731.60,1751.69,11483.29,Posted
3,INV0000004,O0000004,C02311,2024-12-26,6863.98,1235.52,8099.50,Posted
4,INV0000005,O0000005,C03788,2024-12-15,33214.74,5978.65,39193.39,Posted

In [319]:
def validation_check(df):
    valid_total = (
        df['invoice_total'].round(2) ==
        (df['subtotal'] + df['tax_amount']).round(2)
    )

    result = {
        'Duplicate Values': df.duplicated().sum(),
        'Missing values': df.isna().sum().sum(),
        'Unique key': df['invoice_id'].nunique() == len(df),
        'Valid invoice total': valid_total.sum(),
        'Invalid invoice total': (~valid_total).sum(),
        'Reversed invoices': (df['invoice_status'] == 'Reversed').sum(),
        'Posted invoices': (df['invoice_status'] == 'Posted').sum()
    }

    return pd.DataFrame(result.items(), columns=['Check', 'Count'])

In [320]:
validation_check(finance_invoices)

                   Check  Count
0       Duplicate Values      0
1         Missing values      0
2             Unique key   True
3    Valid invoice total  41087
4  Invalid invoice total     79
5      Reversed invoices    828
6        Posted invoices  40338